### ISSUE TITLE
special channel messages can be interpreted as private messages

### ISSUE THREAD

**Issue by jacob1** [caitlin/cinch-resistancegame#41] opened 2015-10-25 02:49 UTC
This means you could do !mission pass, and everyone would see that you passed the mission, which could really screw up the game depending on how it is used.

The "special channel message" i'm talking about is voice (+) or op (@) messages. You can send one with `/msg +#playresistance !mission pass`, everyone else with voice would be able to see the voice message. Everyone currently playing has voice, so they would all see it. Also, tt does require voice to send this.

When a voice message is received it looks like the channel it was sent to is '+#playresistance'. The bot assumes this was in PM.

I didn't actually test the + version, didn't want to mess with the game or reveal how it worked while a game was going on, but I did send a !mission pass command to @#playresistance and the bot accepted it (and I didn't get a response because I assume it was sent back to @#playresistance, where only ops could see it)

To fix, either the bot framework would have to be fixed (I did not check it at all to see if there was some way to deal with it properly), or the bot could be specifically coded to make sure the channel name doesn't start with @ or +, and if it does it should ignore those.

Edit: the two lines that need to be fixed [line 670](https://github.com/caitlin/cinch-resistancegame/blob/master/lib/cinch/plugins/resistance_game.rb#L670) for !vote, and [line 704](https://github.com/caitlin/cinch-resistancegame/blob/master/lib/cinch/plugins/resistance_game.rb#L704) for !mission. I may try to fix it in a few days if I have time, but I don't know any ruby at all and have never used this bot framework before :P.

**Comment by petertseng** [comment] 2015-10-25 17:20
Yup, confirmed that this is possible to do. Thanks for report.

The problem description is that a Cinch `Message#channel` is nil for +#channel messages whereas it should be non-nil. If that were to be fixed in Cinch, the only thing to be done to fix this problem is to update the Cinch gem version, and then everything will just work. The bot would then correctly respond to +#channel messages with "You MUST vote privately" rather than accepting the vote.

Because of the aforementioned the bot has a difficult time to distinguish between messages sent to +#playresistance and messages sent to #playresistance (you can't tell the difference via `Message#channel`) BUT it is still possible - you have to use `Message#params` because it will have the raw data including `+#playresistance`.

Of the two methods described above it seems much preferable to fix it upstream in Cinch rather than using `Message#params`. The latter seems like an ugly hack. Nevertheless of course those who need an **immediate** fix can indeed use the latter method. I suggest that be kept on a separate branch and not master.

For historical context, recall that it used to be possible to send `!mission pass` to #playresistance before https://github.com/caitlin/cinch-resistancegame/pull/36 was merged. That is obviously against the rules (it's like playing your mission card face up in a face-to-face game), it's just that the bot had not been enforcing that particular rule and it was up to humans to say "No you can't vote publicly".

Looks like we are in the same situation now. The bot is failing to properly enforce the rules of the game, and that should absolutely be fixed. Until it is fixed, we can at least tell players that sending messages to +#playresistance is against the rules. So this problem has both a social aspect and a technical aspect.

**Comment by dominikh** [comment] 2015-10-25 18:16
This will be fixed in Cinch today. The planned semantics for a message sent to `+#channel` will be:

- `Message#channel` will return a Channel object for `#channel`
- `Message#reply` will reply to `+#channel`
- A new attribute (tentatively called `Message#statusmsg_mode`) will hold the mode to which the message was sent. `"o"` for ops, `"v"` for voiced. It will be `nil` when the message was sent to `#channel`.

**Comment by jacob1** [comment] 2015-10-25 22:12
Glad this is getting fixed in Cinch, that was the best option :), once you do those changes I don't think the resistance game will need any updates.

**Comment by dominikh** [comment] 2015-10-26 00:34
I've just released version 2.3.0 of Cinch, which should fix the issue.

**Comment by petertseng** [comment] 2015-10-26 03:14
confirmed GOOD behavior of `Message#channel` and `Message#reply` on `+#channel` messages. I may test on this plugin to make sure (shortly), but I expect there will be no issues given the above observation.

Obviously, whoever are running current bots should update Cinch to 2.3.0 to fix this issue on their instance of the bot.

**Comment by jacob1** [comment] 2015-10-26 05:07
OK, good. I've just been playing on freenode, everyone there has some amount of sense and nobody has abused the bug :P

**Comment by petertseng** [comment] 2015-11-04 21:10
Tested on a bot with cinch 2.3.1, and `/msg +#channel !vote yes` are correctly responded to with "You MUST vote privately." Thanks everyone.

**Closed by petertseng** 2015-11-04 21:10 UTC
